version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./db_data:/db_data
        networks:
            - code-network
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        image: php:fpm
        restart: always
        volumes:
            - ./src:/src
        networks:
            - code-network
    db:
        image: postrges:9.5.5
        restart: always
        ports:
            - "5432:5432"
        #environment:
        #    MYSQL_ROOT_PASSWORD: 123456
        #    MYSQL_USER: dev
        #    MYSQL_PASSWORD: 123456
        #    MYSQL_DATABASE: myapp
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks:
            - code-network
networks:
    code-network:
        driver: bridge