version: '2'
services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
            - ./db_data:/db_data
        networks:
            - code-network
    php:
        image: andrdru/php-fpm
        restart: always
        volumes:
            - ./src:/src
            - /var/www/.ssh:/var/www/.ssh
            - ./config/exim4/update-exim4.conf.conf:/etc/exim4/update-exim4.conf.conf
            - ./config/exim4/mailname:/etc/mailname
        networks:
            - code-network
    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: myappdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: pleasechangeme
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
