version: '2'
services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./db_data:/db_data
        networks:
            - code-network
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        image: php:fpm
        restart: always
        volumes:
            - ./src:/src
        networks:
            - code-network
    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: myappdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: pleasechangeme
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
