version: '2'
services:

    web:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
            - ./db_data:/db_data
        networks:
            - code-network

    php:
        image: andrdru/php-fpm
        restart: always
        volumes:
            - ./src:/src
            - /var/www/.ssh:/var/www/.ssh
            - ./config/php/conf.ini:/usr/local/etc/php/conf.d/conf.ini
            - ./config/php/extension.ini:/usr/local/etc/php/conf.d/extension.ini
            - ./config/exim4/update-exim4.conf.conf:/etc/exim4/update-exim4.conf.conf
            - ./config/exim4/mailname:/etc/mailname
        networks:
            - code-network

    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - ./docker-compose.env
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks:
            - code-network

#    apidoc:
#        image: andrdru/apidoc
#        volumes:
#            - ./src:/apidoc
#        networks:
#            - code-network
networks:
    code-network:
        driver: bridge
